name: Auto Approve Release Please PR

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release-please--')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto Approve PR
        id: auto-approve
        continue-on-error: true
        uses: ./
        with:
          github-token: ${{ secrets.CODE_OWNER_TOKEN }}
          allowed-authors: "app/lekman-release-please-bot"
          required-labels: "autorelease: pending"
          label-match-mode: "all"
          path-filters: ".github/release-manifest.json,**/CHANGELOG.md,CHANGELOG.md"
