name: Auto Approve Release Please PR

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'release-please-*'

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto Approve PR
        uses: ./
        with:
          github-token: ${{ secrets.CODE_OWNER_TOKEN }}
          allowed-authors: "Lekman-Release-Please-Bot[bot]"
          required-labels: "autorelease: pending"
          label-match-mode: "all"
          wait-for-checks: true 