name: Test Input Validation

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    paths:
      - 'scripts/validate-inputs.sh'
      - 'action.yml'
      - '.github/workflows/test-input-validation.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  test-valid-inputs:
    name: Test Valid Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test with minimal valid inputs
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-authors: 'user1,user2,dependabot[bot]'
          label-match-mode: 'none'
      
      - name: Test with all valid inputs
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-authors: 'user1,user2,renovate[bot]'
          required-labels: 'approved,ready'
          label-match-mode: 'all'
          wait-for-checks: 'true'
          max-wait-time: '60'
          required-checks: 'CI Build,Unit Tests'

  test-invalid-allowed-authors:
    name: Test Invalid Allowed Authors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test missing allowed-authors
        id: missing-authors
        continue-on-error: true
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Verify failure
        if: steps.missing-authors.outcome != 'failure'
        run: exit 1

  test-invalid-label-match-mode:
    name: Test Invalid Label Match Mode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test invalid label-match-mode
        id: invalid-mode
        continue-on-error: true
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-authors: 'user1'
          label-match-mode: 'invalid'
      
      - name: Verify failure
        if: steps.invalid-mode.outcome != 'failure'
        run: exit 1

  test-invalid-wait-for-checks:
    name: Test Invalid Wait For Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test invalid wait-for-checks
        id: invalid-wait
        continue-on-error: true
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-authors: 'user1'
          wait-for-checks: 'yes'  # Should be true/false
      
      - name: Verify failure
        if: steps.invalid-wait.outcome != 'failure'
        run: exit 1

  test-invalid-max-wait-time:
    name: Test Invalid Max Wait Time
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test negative max-wait-time
        id: negative-time
        continue-on-error: true
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-authors: 'user1'
          max-wait-time: '-5'
      
      - name: Verify failure
        if: steps.negative-time.outcome != 'failure'
        run: exit 1
      
      - name: Test excessive max-wait-time
        id: excessive-time
        continue-on-error: true
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-authors: 'user1'
          max-wait-time: '500'  # Over 360 minutes limit
      
      - name: Verify failure
        if: steps.excessive-time.outcome != 'failure'
        run: exit 1

  test-label-mode-validation:
    name: Test Label Mode Validation Rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test label-match-mode 'all' without labels
        id: all-without-labels
        continue-on-error: true
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-authors: 'user1'
          label-match-mode: 'all'
          # required-labels not provided
      
      - name: Verify failure
        if: steps.all-without-labels.outcome != 'failure'
        run: exit 1
      
      - name: Test label-match-mode 'none' with labels
        id: none-with-labels
        continue-on-error: true
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-authors: 'user1'
          required-labels: 'do-not-merge'
          label-match-mode: 'none'
      
      - name: Verify failure
        if: steps.none-with-labels.outcome != 'failure'
        run: exit 1